--- #YAML:1.0
name:               Acme-AsciiArtFarts
version:            0.03
abstract:           Simple Object Interface to AsciiArtFarts
author:
    - Luke Poskitt <ltp@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP:         0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
